(function privacyDossierPage() {
  const STORAGE_LANG_KEY = "pipboy_lang";
  const loader = window.createDossierLoader?.({ minDelayMs: 700 }) || {
    ready() {},
    fail() {}
  };
  const CONTENT = {
    en: {
      pageTitle: "Privacy Policy | Fallout Codex Bot",
      metaDescription:
        "Privacy Policy for the Fallout Codex Discord bot, including what data is stored, how it is used, and how subscriptions are managed.",
      loaderKicker: "FALLOUT CODEX // BOT DIRECTIVE",
      loaderTitle: "LOADING PRIVACY INTEL",
      loaderCopy: "Assembling data-handling records and relay policy fragments...",
      langLabel: "LANGUAGE",
      eyebrow: "FALLOUT CODEX // DATA HANDLING INTEL",
      title: "PRIVACY POLICY",
      summary:
        "This policy explains what the Fallout Codex Discord bot stores, what it uses that data for, and how subscription and interaction data are handled when the bot posts silo code and Minerva intel.",
      chips: ["DISCORD BOT", "COMMUNITY INTEL", "LAST UPDATED MARCH 9, 2026"],
      side: {
        label: "POLICY SCOPE",
        value: "BOT + SUPPORT PAGES",
        copy:
          "Applies to the Fallout Codex Discord bot, its slash commands, related bot documentation pages, and the linked Fallout Codex site used to preview or explain bot features."
      },
      actions: {
        primary: "VIEW TERMS OF SERVICE",
        secondary: "RETURN TO FALLOUT CODEX"
      },
      navKicker: "SECTION INDEX",
      footerNote:
        "This page describes the Fallout Codex bot's current operational behavior as of March 9, 2026.",
      stats: [
        ["STORED IDENTIFIERS", "SERVER + CHANNEL IDS", "Used to know where subscribed intel should be posted."],
        ["MESSAGE ACCESS", "NO ROUTINE SCANNING", "The bot is not built to routinely read or archive ordinary server chat."],
        ["PREFERENCES", "SERVER LANGUAGE", "Guild language settings are stored so embeds and replies can stay in EN or ES."],
        ["RUNTIME DATA", "TEMPORARY INTERACTION STATE", "Small in-memory interaction state may be used to manage ephemeral Minerva item details."]
      ],
      sections: [
        {
          id: "privacy-collected",
          kicker: "01 // INFORMATION WE COLLECT",
          title: "What the bot stores",
          copies: [
            "The Fallout Codex bot stores a limited set of Discord-related metadata so it can deliver intel updates and remember server preferences."
          ],
          list: [
            "Discord server IDs and target channel IDs for channels subscribed to bot updates.",
            "Subscribed feed preferences, such as silo codes, Minerva intel, or both.",
            "Server language settings so the bot can respond in English or Spanish.",
            "Basic command-related metadata such as the user who created a subscription, selected feed, and locale.",
            "Temporary in-memory interaction state used to replace or refresh ephemeral Minerva item detail replies.",
            "Operational state used to prevent duplicate broadcasts when silo codes or Minerva status have not changed.",
            "Basic diagnostic and error logs needed to keep the service working and investigate failures or abuse."
          ],
          navLabel: "Information We Collect"
        },
        {
          id: "privacy-usage",
          kicker: "02 // HOW WE USE DATA",
          title: "Why the bot needs it",
          list: [
            "To post silo code and Minerva updates into the channels that a server selected.",
            "To remember which servers prefer English or Spanish responses.",
            "To generate slash command previews, item detail responses, and subscription status summaries.",
            "To avoid reposting unchanged intel and spamming the same channel repeatedly.",
            "To diagnose outages, permission problems, bad upstream responses, or malformed subscriptions."
          ],
          navLabel: "How We Use Data"
        },
        {
          id: "privacy-not-collected",
          kicker: "03 // DATA LIMITS",
          title: "What we do not collect",
          list: [
            "No passwords, payment information, or billing data.",
            "No routine collection or archival of normal server message content.",
            "No sale of personal data to advertisers or data brokers.",
            "No marketing mailing lists or unrelated direct-message campaigns generated by the bot."
          ],
          note:
            "The bot may process the content of bot commands and component interactions that users intentionally send to it, but it is not designed as a message logging tool.",
          navLabel: "What We Do Not Collect"
        },
        {
          id: "privacy-retention",
          kicker: "04 // RETENTION + DELETION",
          title: "How long data stays",
          copies: [
            "Subscription records, language settings, and anti-duplicate broadcast state may remain stored while the bot is active and configured in a server. These records can be removed by unsubscribing channels, clearing the bot from a server, or by administrative cleanup by the bot operator."
          ],
          list: [
            "Subscription and server preference data may persist across restarts when persistent storage is enabled.",
            "Broadcast fingerprints may be retained to prevent repeated posts of unchanged intel.",
            "Temporary interaction mappings used for ephemeral item detail replies are kept in runtime memory and are not intended as long-term records."
          ],
          navLabel: "Retention and Deletion"
        },
        {
          id: "privacy-sharing",
          kicker: "05 // THIRD PARTIES",
          title: "Services and sources involved",
          copies: [
            "The bot depends on Discord itself, its hosting environment, and upstream intel sources used to build Fallout 76 status updates. Depending on the feature, those sources may include Fallout Codex web assets, NukaCrypt, WhereIsMinerva, and Fallout Fandom pages used for item references.",
            "We do not sell subscription metadata. Data may still be processed by hosting providers, Discord, or other third parties as part of operating the service or if required by law."
          ],
          navLabel: "Third Parties"
        },
        {
          id: "privacy-security",
          kicker: "06 // SECURITY",
          title: "How data is protected",
          copies: [
            "Reasonable technical steps are used to protect stored bot data, including limiting stored data to what is needed for bot operations and keeping runtime state small. However, no online service or storage environment can guarantee perfect security."
          ],
          navLabel: "Security"
        },
        {
          id: "privacy-changes",
          kicker: "07 // POLICY UPDATES",
          title: "Changes to this policy",
          copies: [
            "This Privacy Policy may be updated as the bot changes, adds features, or changes how it stores operational data. Continued use of the bot after updates means you accept the revised policy."
          ],
          note: "If your server no longer agrees with this policy, remove the bot and clear any existing subscriptions.",
          navLabel: "Policy Updates"
        }
      ]
    },
    es: {
      pageTitle: "Politica de Privacidad | Fallout Codex Bot",
      metaDescription:
        "Politica de Privacidad para el bot de Discord Fallout Codex, incluyendo que datos se guardan, como se usan y como se gestionan las suscripciones.",
      loaderKicker: "FALLOUT CODEX // DIRECTIVA DEL BOT",
      loaderTitle: "CARGANDO INTEL DE PRIVACIDAD",
      loaderCopy: "Ensamblando registros de manejo de datos y fragmentos de politica del relay...",
      langLabel: "IDIOMA",
      eyebrow: "FALLOUT CODEX // INTEL DE MANEJO DE DATOS",
      title: "POLITICA DE PRIVACIDAD",
      summary:
        "Esta politica explica que guarda el bot de Discord Fallout Codex, para que usa esos datos y como se manejan las suscripciones e interacciones cuando el bot publica intel de silos y de Minerva.",
      chips: ["BOT DE DISCORD", "INTEL COMUNITARIO", "ACTUALIZADO 9 DE MARZO DE 2026"],
      side: {
        label: "ALCANCE DE LA POLITICA",
        value: "BOT + PAGINAS DE APOYO",
        copy:
          "Aplica al bot de Discord Fallout Codex, sus comandos slash, sus paginas de documentacion relacionadas y al sitio de Fallout Codex enlazado para previsualizar o explicar funciones del bot."
      },
      actions: {
        primary: "VER TERMINOS DE SERVICIO",
        secondary: "VOLVER A FALLOUT CODEX"
      },
      navKicker: "INDICE DE SECCIONES",
      footerNote:
        "Esta pagina describe el comportamiento operativo actual del bot Fallout Codex al 9 de marzo de 2026.",
      stats: [
        ["IDENTIFICADORES GUARDADOS", "IDS DE SERVIDOR + CANAL", "Se usan para saber donde debe publicarse el intel suscrito."],
        ["ACCESO A MENSAJES", "SIN ESCANEO RUTINARIO", "El bot no esta hecho para leer ni archivar el chat normal del servidor."],
        ["PREFERENCIAS", "IDIOMA DEL SERVIDOR", "Se guarda el idioma del guild para mantener embeds y respuestas en EN o ES."],
        ["DATOS EN EJECUCION", "ESTADO TEMPORAL DE INTERACCION", "Puede usarse un pequeno estado en memoria para detalles efimeros de items de Minerva."]
      ],
      sections: [
        {
          id: "privacy-collected",
          kicker: "01 // INFORMACION QUE RECOPILAMOS",
          title: "Que guarda el bot",
          copies: [
            "El bot Fallout Codex guarda un conjunto limitado de metadatos relacionados con Discord para poder enviar actualizaciones de intel y recordar preferencias del servidor."
          ],
          list: [
            "IDs de servidor de Discord y IDs de canal destino para canales suscritos a actualizaciones del bot.",
            "Preferencias de feed suscrito, como codigos de silos, intel de Minerva o ambos.",
            "Ajustes de idioma del servidor para que el bot pueda responder en ingles o espanol.",
            "Metadatos basicos ligados a comandos, como el usuario que creo una suscripcion, el feed elegido y la configuracion regional.",
            "Estado temporal en memoria usado para reemplazar o refrescar respuestas efimeras de detalles de items de Minerva.",
            "Estado operativo usado para evitar emisiones duplicadas cuando los codigos de silos o el estado de Minerva no han cambiado.",
            "Registros basicos de diagnostico y error necesarios para mantener el servicio funcionando e investigar fallos o abuso."
          ],
          navLabel: "Informacion que recopilamos"
        },
        {
          id: "privacy-usage",
          kicker: "02 // COMO USAMOS LOS DATOS",
          title: "Por que el bot los necesita",
          list: [
            "Para publicar actualizaciones de codigos de silos y Minerva en los canales que un servidor eligio.",
            "Para recordar que servidores prefieren respuestas en ingles o espanol.",
            "Para generar previews de comandos slash, respuestas de detalle de items y resumenes del estado de suscripciones.",
            "Para evitar republicar intel sin cambios y saturar el mismo canal repetidamente.",
            "Para diagnosticar caidas, problemas de permisos, respuestas defectuosas de fuentes externas o suscripciones mal formadas."
          ],
          navLabel: "Como usamos los datos"
        },
        {
          id: "privacy-not-collected",
          kicker: "03 // LIMITES DE DATOS",
          title: "Lo que no recopilamos",
          list: [
            "No contrasenas, informacion de pago ni datos de facturacion.",
            "No recopilacion ni archivo rutinario del contenido normal de mensajes del servidor.",
            "No venta de datos personales a anunciantes o corredores de datos.",
            "No listas de marketing ni campanas de mensajes directos no relacionadas generadas por el bot."
          ],
          note:
            "El bot puede procesar el contenido de comandos e interacciones que los usuarios le envian intencionalmente, pero no esta disenado como una herramienta de registro de mensajes.",
          navLabel: "Lo que no recopilamos"
        },
        {
          id: "privacy-retention",
          kicker: "04 // RETENCION + ELIMINACION",
          title: "Cuanto tiempo permanecen los datos",
          copies: [
            "Los registros de suscripciones, ajustes de idioma y estado anti-duplicados pueden seguir guardados mientras el bot este activo y configurado en un servidor. Estos registros pueden eliminarse al cancelar suscripciones de canales, sacar el bot de un servidor o mediante limpieza administrativa por parte del operador."
          ],
          list: [
            "Los datos de suscripcion y preferencias del servidor pueden persistir entre reinicios cuando el almacenamiento persistente esta habilitado.",
            "Las huellas de emisiones pueden conservarse para evitar publicaciones repetidas de intel sin cambios.",
            "Los mapeos temporales de interaccion usados para respuestas efimeras de detalle de items se guardan en memoria de ejecucion y no estan pensados como registros a largo plazo."
          ],
          navLabel: "Retencion y eliminacion"
        },
        {
          id: "privacy-sharing",
          kicker: "05 // TERCEROS",
          title: "Servicios y fuentes involucradas",
          copies: [
            "El bot depende de Discord, de su entorno de alojamiento y de fuentes externas de intel usadas para construir actualizaciones de estado de Fallout 76. Segun la funcion, esas fuentes pueden incluir recursos web de Fallout Codex, NukaCrypt, WhereIsMinerva y paginas de Fallout Fandom usadas como referencia de items.",
            "No vendemos metadatos de suscripcion. Aun asi, los datos pueden ser procesados por proveedores de alojamiento, Discord u otros terceros como parte de operar el servicio o si la ley lo exige."
          ],
          navLabel: "Terceros"
        },
        {
          id: "privacy-security",
          kicker: "06 // SEGURIDAD",
          title: "Como se protegen los datos",
          copies: [
            "Se usan medidas tecnicas razonables para proteger los datos guardados por el bot, incluyendo limitar los datos a lo necesario para la operacion y mantener pequeno el estado en tiempo de ejecucion. Sin embargo, ningun servicio online o entorno de almacenamiento puede garantizar seguridad perfecta."
          ],
          navLabel: "Seguridad"
        },
        {
          id: "privacy-changes",
          kicker: "07 // ACTUALIZACIONES DE LA POLITICA",
          title: "Cambios a esta politica",
          copies: [
            "Esta Politica de Privacidad puede actualizarse a medida que cambie el bot, anada funciones o modifique la forma en que guarda datos operativos. El uso continuo del bot despues de las actualizaciones significa que aceptas la politica revisada."
          ],
          note: "Si tu servidor ya no esta de acuerdo con esta politica, elimina el bot y borra las suscripciones existentes.",
          navLabel: "Actualizaciones de la politica"
        }
      ]
    }
  };

  const elements = {
    metaDescription: document.getElementById("legalMetaDescription"),
    pageEyebrow: document.getElementById("legalPageEyebrow"),
    pageTitle: document.getElementById("legalPageTitle"),
    pageSummary: document.getElementById("legalPageSummary"),
    chipRow: document.getElementById("legalChipRow"),
    langLabel: document.getElementById("legalLangLabel"),
    langButtons: Array.from(document.querySelectorAll("[data-lang-option]")),
    sideLabel: document.getElementById("legalSideLabel"),
    sideValue: document.getElementById("legalSideValue"),
    sideCopy: document.getElementById("legalSideCopy"),
    primaryAction: document.getElementById("legalPrimaryAction"),
    secondaryAction: document.getElementById("legalSecondaryAction"),
    statGrid: document.getElementById("legalStatGrid"),
    mainContent: document.getElementById("legalMainContent"),
    navKicker: document.getElementById("legalNavKicker"),
    navList: document.getElementById("legalNavList"),
    footerNote: document.getElementById("legalFooterNote")
  };

  function normalizeLanguage(value) {
    return String(value || "").trim().toLowerCase().startsWith("es") ? "es" : "en";
  }

  function detectLanguage() {
    const params = new URLSearchParams(window.location.search);
    const fromQuery = params.get("lang");
    const fromStorage = safeStorageGet(STORAGE_LANG_KEY);
    return normalizeLanguage(fromQuery || fromStorage || navigator.language || "en");
  }

  function safeStorageGet(key) {
    try {
      return window.localStorage.getItem(key);
    } catch (_error) {
      return "";
    }
  }

  function safeStorageSet(key, value) {
    try {
      window.localStorage.setItem(key, value);
    } catch (_error) {
      return;
    }
  }

  function createElement(tagName, className, text) {
    const element = document.createElement(tagName);
    if (className) {
      element.className = className;
    }
    if (typeof text === "string") {
      element.textContent = text;
    }
    return element;
  }

  function renderChips(chips) {
    elements.chipRow.replaceChildren(...chips.map((chip) => createElement("span", "legal-chip", chip)));
  }

  function renderStats(stats) {
    const nodes = stats.map(([label, value, copy]) => {
      const card = createElement("article", "legal-stat-card");
      card.append(
        createElement("p", "legal-stat-label", label),
        createElement("p", "legal-stat-value", value),
        createElement("p", "legal-stat-copy", copy)
      );
      return card;
    });
    elements.statGrid.replaceChildren(...nodes);
  }

  function renderSections(sections) {
    const nodes = sections.map((section) => {
      const card = createElement("section", "legal-section-card");
      card.id = section.id;
      card.append(
        createElement("p", "legal-section-kicker", section.kicker),
        createElement("h2", "legal-section-title", section.title)
      );

      for (const copy of section.copies || []) {
        card.append(createElement("p", "legal-section-copy", copy));
      }

      if (Array.isArray(section.list) && section.list.length) {
        const list = createElement("ul", "legal-section-list");
        for (const item of section.list) {
          list.append(createElement("li", "", item));
        }
        card.append(list);
      }

      if (section.note) {
        card.append(createElement("p", "legal-section-note", section.note));
      }

      return card;
    });

    elements.mainContent.replaceChildren(...nodes);
  }

  function renderNav(sections) {
    const nodes = sections.map((section, index) => {
      const link = createElement("a", "legal-nav-link");
      link.href = `#${section.id}`;
      link.append(
        createElement("strong", "", String(index + 1).padStart(2, "0")),
        createElement("span", "", section.navLabel)
      );
      return link;
    });

    elements.navList.replaceChildren(...nodes);
  }

  function applyLanguage(lang, persist = true) {
    const dictionary = CONTENT[normalizeLanguage(lang)] || CONTENT.en;

    document.documentElement.lang = normalizeLanguage(lang);
    document.title = dictionary.pageTitle;
    window.setDossierLoaderText?.({
      kicker: dictionary.loaderKicker,
      title: dictionary.loaderTitle,
      copy: dictionary.loaderCopy
    });
    elements.metaDescription?.setAttribute("content", dictionary.metaDescription);
    elements.pageEyebrow.textContent = dictionary.eyebrow;
    elements.pageTitle.textContent = dictionary.title;
    elements.pageSummary.textContent = dictionary.summary;
    elements.langLabel.textContent = dictionary.langLabel;
    elements.sideLabel.textContent = dictionary.side.label;
    elements.sideValue.textContent = dictionary.side.value;
    elements.sideCopy.textContent = dictionary.side.copy;
    elements.primaryAction.textContent = dictionary.actions.primary;
    elements.secondaryAction.textContent = dictionary.actions.secondary;
    elements.navKicker.textContent = dictionary.navKicker;
    elements.footerNote.textContent = dictionary.footerNote;

    renderChips(dictionary.chips);
    renderStats(dictionary.stats);
    renderSections(dictionary.sections);
    renderNav(dictionary.sections);

    elements.langButtons.forEach((button) => {
      const isActive = button.dataset.langOption === normalizeLanguage(lang);
      button.classList.toggle("is-active", isActive);
      button.setAttribute("aria-pressed", isActive ? "true" : "false");
    });

    if (persist) {
      safeStorageSet(STORAGE_LANG_KEY, normalizeLanguage(lang));
    }
  }

  elements.langButtons.forEach((button) => {
    button.addEventListener("click", () => applyLanguage(button.dataset.langOption || "en"));
  });

  applyLanguage(detectLanguage(), false);
  loader.ready();
})();
